import type { LectureData } from './types'
import { Palma, Papa, Pina, Pino } from '@/assets/P-Papa'

export const papaLecture: LectureData = {
  letter: 'p',
  mainImage: Papa,
  content: [

    [
      { type: 'word', text: 'papá', highlight: true },
    ],

    [
      { type: 'word', text: 'el' },
      { type: 'space' },
      { type: 'word', text: 'papá' },
      { type: 'space' },
      { type: 'word', text: 'de' },
      { type: 'space' },
      { type: 'word', text: 'pepe' },
      { type: 'space' },
      { type: 'word', text: 'poda' },
      { type: 'space' },
      { type: 'word', text: 'los' },
      { type: 'space' },
      { type: 'image', src: Pino }, // pinos
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'los' },
      { type: 'space' },
      { type: 'word', text: 'nenes' },
      { type: 'space' },
      { type: 'word', text: 'le' },
      { type: 'space' },
      { type: 'word', text: 'piden' },
      { type: 'space' },
      { type: 'image', src: Pina }, // piñas
      { type: 'space' },
      { type: 'word', text: 'y' },
      { type: 'space' },
      { type: 'word', text: 'pepinos' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'una' },
      { type: 'space' },
      { type: 'word', text: 'paloma' },
      { type: 'space' },
      { type: 'word', text: 'posó' },
      { type: 'space' },
      { type: 'word', text: 'en' },
      { type: 'space' },
      { type: 'word', text: 'una' },
      { type: 'space' },
      { type: 'image', src: Palma },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'puso' },
      { type: 'space' },
      { type: 'word', text: 'su' },
      { type: 'space' },
      { type: 'word', text: 'nido' },
      { type: 'space' },
      { type: 'word', text: 'después' },
      { type: 'space' },
      { type: 'word', text: 'en' },
      { type: 'space' },
      { type: 'word', text: 'un' },
      { type: 'space' },
      { type: 'word', text: 'pino' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'al' },
      { type: 'space' },
      { type: 'word', text: 'puma' },
      { type: 'space' },
      { type: 'word', text: 'le' },
      { type: 'space' },
      { type: 'word', text: 'pidió' },
      { type: 'space' },
      { type: 'word', text: 'mil' },
      { type: 'space' },
      { type: 'word', text: 'pelos' },
    ],[
      { type: 'space' },
      { type: 'word', text: 'de' },
      { type: 'space' },
      { type: 'word', text: 'su' },
      { type: 'space' },
      { type: 'word', text: 'piel,' },
      { type: 'space' },
      { type: 'word', text: 'el' },
      { type: 'space' },
      { type: 'word', text: 'puma' },
      { type: 'space' },
      { type: 'word', text: 'se' },
      { type: 'space' },
      { type: 'word', text: 'los' },
      { type: 'space' },
      { type: 'word', text: 'dio' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'al' },
      { type: 'space' },
      { type: 'word', text: 'sapo' },
      { type: 'space' },
      { type: 'word', text: 'le' },
      { type: 'space' },
      { type: 'word', text: 'pidió' },
      { type: 'space' },
      { type: 'word', text: 'dos' },
      { type: 'space' },
      { type: 'word', text: 'mil' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'no' },
      { type: 'space' },
      { type: 'word', text: 'puede' },
      { type: 'space' },
      { type: 'word', text: 'el' },
      { type: 'space' },
      { type: 'word', text: 'sapito,' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'el' },
      { type: 'space' },
      { type: 'word', text: 'pelo' },
      { type: 'space' },
      { type: 'word', text: 'no' },
      { type: 'space' },
      { type: 'word', text: 'sale' },
      { type: 'space' },
      { type: 'word', text: 'en' },
      { type: 'space' },
      { type: 'word', text: 'su' },
      { type: 'space' },
      { type: 'word', text: 'piel' },
      { type: 'space' },
    ],

  ],
}
