import type { LectureData } from './types'
import { Bolso, Oso, Reboso, Rosa, Sol, Sombrero } from '@/assets/S-Sol'

export const solLecture: LectureData = {
  letter: 's',
  mainImage: Sol,
  content: [

    [
      { type: 'word', text: 'sol', highlight: true },
    ],

    [
      { type: 'word', text: 'usa' },
      { type: 'space' },
      { type: 'image', src: Bolso },
      { type: 'space' },
      { type: 'word', text: 'esa' },
      { type: 'space' },
      { type: 'word', text: 'osa' },
      { type: 'space' },
    ],
    [
      { type: 'word', text: 'y' },
      { type: 'space' },
      { type: 'word', text: 'su' },
      { type: 'space' },
      { type: 'image', src: Sombrero },
      { type: 'space' },
      { type: 'word', text: 'ese' },
      { type: 'space' },
      { type: 'word', text: 'oso' },
      { type: 'space' },
    ],
    [
      { type: 'word', text: 'asi' },
      { type: 'space' },
      { type: 'word', text: 'es' },
      { type: 'space' },
      { type: 'word', text: 'esa' },
      { type: 'space' },
      { type: 'image', src: Rosa },
      { type: 'space' },
    ],
    [
      { type: 'word', text: 'y' },
      { type: 'space' },
      { type: 'word', text: 'asi' },
      { type: 'space' },
      { type: 'word', text: 'ese' },
      { type: 'space' },
      { type: 'image', src: Reboso },
      { type: 'space' },
    ],
    [

      { type: 'image', src: Oso },
    ],
    [
      { type: 'space' },
      { type: 'word', text: 'la' },
      { type: 'space' },
      { type: 'word', text: 'la' },
      { type: 'space' },
      { type: 'word', text: 'la' },
      { type: 'space' },
    ],
    [
      { type: 'space' },
      { type: 'word', text: 'ese' },
      { type: 'space' },
      { type: 'word', text: 'oso' },
      { type: 'space' },
      { type: 'word', text: 'se' },
      { type: 'space' },
      { type: 'word', text: 'asea' },
      { type: 'space' },
    ],
    [
      { type: 'space' },
      { type: 'word', text: 'la' },
      { type: 'space' },
      { type: 'word', text: 'la' },
      { type: 'space' },
      { type: 'word', text: 'la' },
      { type: 'space' },
    ],
    [
      { type: 'space' },
      { type: 'word', text: 'esa' },
      { type: 'space' },
      { type: 'word', text: 'osa' },
      { type: 'space' },
      { type: 'word', text: 'se' },
      { type: 'space' },
      { type: 'word', text: 'asea' },
      { type: 'space' },
    ],
    [
      { type: 'space' },
      { type: 'word', text: 'oso' },
      { type: 'space' },
      { type: 'word', text: 'osa' },
      { type: 'space' },
      { type: 'word', text: 'isa' },
      { type: 'space' },
    ],
    [
      { type: 'space' },
      { type: 'word', text: 'ese' },
      { type: 'space' },
      { type: 'word', text: 'oso' },
      { type: 'space' },
      { type: 'word', text: 'ese' },
      { type: 'space' },
      { type: 'word', text: 'osa' },
      { type: 'space' },
    ],
  ],
}
