import type { LectureData } from './types'
import { Pato, Tehuacan, TioTian } from '@/assets/T-TioTian'

export const tioTianLecture: LectureData = {
  letter: 't',
  mainImage: TioTian,
  content: [

    [
      { type: 'word', text: 'el' },
      { type: 'space' },
      { type: 'word', text: 'tío', highlight: true },
      { type: 'space' },
      { type: 'word', text: 'tián', highlight: true },
    ],

    [
      { type: 'word', text: 'tin' },
      { type: 'space' },
      { type: 'word', text: 'tan' },
      { type: 'space' },
      { type: 'word', text: 'tin' },
      { type: 'space' },
      { type: 'word', text: 'tan' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'los' },
      { type: 'space' },
      { type: 'word', text: 'patitos' },
      { type: 'space' },
      { type: 'word', text: 'del' },
      { type: 'space' },
      { type: 'word', text: 'tío' },
      { type: 'space' },
      { type: 'word', text: 'tián' },
      { type: 'space' },
      { type: 'image', src: Pato },
    ],

    [
      { type: 'word', text: 'tienen' },
      { type: 'space' },
      { type: 'word', text: 'sed' },
      { type: 'space' },
      { type: 'word', text: 'y' },
      { type: 'space' },
      { type: 'word', text: 'no' },
      { type: 'space' },
      { type: 'word', text: 'les' },
      { type: 'space' },
      { type: 'word', text: 'dan' },
      { type: 'space' },
      { type: 'word', text: 'ni' },
      { type: 'space' },
      { type: 'word', text: 'tantito' },
      { type: 'space' },
      { type: 'image', src: Tehuacan }, // botella / tehuacán
      { type: 'space' },
      { type: 'word', text: '(tehuacan)' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'el' },
      { type: 'space' },
      { type: 'word', text: 'tío' },
      { type: 'space' },
      { type: 'word', text: 'tián' },
      { type: 'space' },
      { type: 'word', text: 'tenía' },
      { type: 'space' },
      { type: 'word', text: 'un' },
      { type: 'space' },
      { type: 'word', text: 'patito' },
      { type: 'space' },
      { type: 'word', text: 'pinto' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'el' },
      { type: 'space' },
      { type: 'word', text: 'patito' },
      { type: 'space' },
      { type: 'word', text: 'salía' },
      { type: 'space' },
      { type: 'word', text: 'a' },
      { type: 'space' },
      { type: 'word', text: 'paseo' },
      { type: 'space' },
      { type: 'word', text: 'todos' },
      { type: 'space' },
      { type: 'word', text: 'los' },
      { type: 'space' },
      { type: 'word', text: 'días.' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'ese' },
      { type: 'space' },
      { type: 'word', text: 'patito' },
      { type: 'space' },
      { type: 'word', text: 'es' },
      { type: 'space' },
      { type: 'word', text: 'tonto,' },
      { type: 'space' },
      { type: 'word', text: 'no' },
      { type: 'space' },
      { type: 'word', text: 'nada,' },
      { type: 'space' },
      { type: 'word', text: 'no' },
      { type: 'space' },
      { type: 'word', text: 'nada.' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'el' },
      { type: 'space' },
      { type: 'word', text: 'tío' },
      { type: 'space' },
      { type: 'word', text: 'tián' },
      { type: 'space' },
      { type: 'word', text: 'lo' },
      { type: 'space' },
      { type: 'word', text: 'puso' },
      { type: 'space' },
      { type: 'word', text: 'en' },
      { type: 'space' },
      { type: 'word', text: 'una' },
      { type: 'space' },
      { type: 'word', text: 'tina' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: '¡sí' },
      { type: 'space' },
      { type: 'word', text: 'nada!' },
      { type: 'space' },
      { type: 'word', text: '¡sí' },
      { type: 'space' },
      { type: 'word', text: 'nada!' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'tiene' },
      { type: 'space' },
      { type: 'word', text: 'unas' },
      { type: 'space' },
      { type: 'word', text: 'telitas' },
      { type: 'space' },
      { type: 'word', text: 'en' },
      { type: 'space' },
      { type: 'word', text: 'las' },
      { type: 'space' },
      { type: 'word', text: 'patas' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'toma' },
      { type: 'space' },
      { type: 'word', text: 'una' },
      { type: 'space' },
      { type: 'word', text: 'tuna' },
      { type: 'space' },
      { type: 'word', text: 'patito:' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'patito' },
      { type: 'space' },
      { type: 'word', text: 'paleta' },
      { type: 'space' },
      { type: 'word', text: 'petate' },
      { type: 'space' },
    ],

    [
      { type: 'word', text: 'elote' },
      { type: 'space' },
      { type: 'word', text: 'tapete' },
      { type: 'space' },
      { type: 'word', text: 'metate' },
      { type: 'space' },
    ],

  ],
}
